spring:
  application:
    name: EscenaLocal
  datasource:
    url: jdbc:postgresql://localhost:5432/escenadb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update
    show-sql: true


server:
  port:  8080

logging:
  level.org.hibernate.sql=debug
  level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE